apiVersion: v1
kind: NameSpace
metadata:
  name: mysql-ns
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-sv
  nameSpace: mysql-ns
spec:
  clusterIP: None
  selector: 
    app: mysql
  ports:
    - port: 3306