apiVersion: v1
kind: pod
metadata:
  name: imagepull
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: nginx
      imagePullPolicy: Always
      # imagePullPolicy: IfNotPresent
      # imagePullPolicy: Never

---
# Restart Policy

apiVersion: v1
kind: Pod
metadata:
  name: web-service
spec:
  restartPolicy: OnFailure # Only restart on non-zero exit codes
  containers:
    - name: web-server
      image: nginx


# Exit code 0: Job completes successfully, no restart
# Exit code 1+: Container restarts to retry the task
---
