apiVersion: v1
kind: pod
metadata:
  name: imagepull
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: nginx
      imagePullPolicy: Always
      # imagePullPolicy: IfNotPresent
      # imagePullPolicy: Never