apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    kubernetes.io/change-cause: "Initial release with nginx 1.20"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx 
      env: deployment
  template:
    metadata: 
      labels:
        app: nginx 
        env: deployment 
    spec: 
     containers:
      - name: nginx 
        image: nginx:1.20
        ports:
          - containerPort: 80

