apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-1
spec:
  replicas: 20
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      nodeSelector:
        environment: frontend
      containers:
        - name: frontend-app
          image: nginx
          resources:
            requests:
              memory: "10Mi"
              cpu: "50m"
            limits:
              memory: "10Mi"
              cpu: "50m"
